# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9715073e0a337c6a04cb8a3cf81c1700e00637b3d8ddfaf9dd3948bc65a1d9135305644d9cf2d2f6c7eb8331beeacd8c96a73e02bd810085a4264ab599b7b4f

test:
  secret_key_base: 30c31d6e88ff39debc8a92037826b331e24ff16db5f896b31aab66d1a8c47f30bbc48902e6c975c563db987821366e9c91691d1c517db782f787f80cca3da700

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
